export const testGameContextValue={
    playerHand: [],
    playerScore: 0,
    aiHand: [],
    aiScore: 0,
    cardsInDeck: 36,
    drawCard: () => {},
    switchActivePlayer: () => {},
    handleCardRequest: () => {},
    restartGame: () => {},
    message: '',
    cardsLocked: false,
    lockHand: () => {},
    asyncSetState: () => {},
    user_name: '',
    total_points: 10,
    rank: 3,
    totalPlayers: 5,
    team_id: 2,
    ai_team: 1,
  }